apiVersion: apps/v1
kind: Deployment
metadata:
  name: un
spec:
  replicas: 1
  selector:
    matchLabels:
      app: un
  template:
    metadata:
      labels:
        app: un
    spec:
      containers:
      - image: okteto.dev/un:latest
        name: un
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "e24fe32a-dd87-416c-8593-eba2bacc1fa7"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "e24fe32a-dd87-416c-8593-eba2bacc1fa7"
        - name: Vmess_Path
          value: "/add"
        - name: Share_Path
          value: "/share233"
